apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: backend
          image: andrecuau02/missionsim-backend:v1.0.6
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: postgres://your_db_user:your_db_password@postgres:5432/your_db_name
            - name: REDIS_URL
              value: redis://redis:6379
            - name: PORT
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
