apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: frontend
          image: andrecuau02/missionsim-frontend:v1.0.4
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              value: const API_URL = 'http://localhost:8080/api';
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer  # or NodePort if using minikube/local
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80