version: "3.8"
services:
  db:
    image: postgres:16
    container_name: pg_container
    restart: always
    environment:
      POSTGRES_USER: node_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: storage
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: node_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      PGHOST: db
      PGUSER: node_user
      PGPASSWORD: 123456
      PGDATABASE: storage
      PGPORT: 5432
      PORT: 3000
      DATABASE_URL: postgres://node_user:123456@db:5432/storage
      REDIS_URL: redis://redis:6379 # was redis://localhost:6379
    volumes:
      - .:/usr/src/app
        - node_modules:/usr/src/app/node_modules
    command: npm start

volumes:
  pgdata:
  node_modules:
